import type {
  Na3Department,
  Na3DepartmentId,
  Na3DepartmentType,
} from "../modules/na3-types";
import {
  createFactoryAdmDpt,
  createOfficeDpt,
  createShopFloorDpt,
} from "../utils";

export const DEPARTMENTS: {
  [Type in Na3DepartmentType]: Record<
    Na3DepartmentId<Type>,
    Na3Department<Type>
  >;
} = {
  "factory-adm": {
    administrativo: createFactoryAdmDpt({
      apps: ["manut", "transf"],
      displayName: "Administrativo",
      id: "administrativo",
      name: "Administrativo",
      positions: ["gerente-industrial"],
      color: "cyan",
    }),
    manutencao: createFactoryAdmDpt({
      apps: ["manut"],
      displayName: "Manutenção",
      id: "manutencao",
      name: "Manutenção",
      positions: [
        "coordenador-manutencao",
        "eletricista-1",
        "eletricista-2",
        "mecanico-1",
        "mecanico-2",
        "serralheiro-industrial",
        "assistente-manutencao",
        "assistente-compras-manutencao",
      ],
      color: "red",
    }),
    pcp: createFactoryAdmDpt({
      apps: ["manut", "transf"],
      displayName: "PCP",
      id: "pcp",
      name: "Planejamento & Controle da Produção",
      positions: ["assistente-pcp", "assistente-compras-pcp"],
      color: "orange",
    }),
    qualidade: createFactoryAdmDpt({
      apps: ["transf"],
      displayName: "Qualidade",
      id: "qualidade",
      name: "Qualidade",
      positions: [
        "supervisor-qualidade",
        "analista-qualidade",
        "inspetor-qualidade-1",
        "inspetor-qualidade-2",
      ],
      color: "blue",
    }),
  },

  office: {
    comex: createOfficeDpt({
      apps: ["manut", "transf"],
      displayName: "Comércio Exterior",
      id: "comex",
      name: "Comércio Exterior",
      positions: [],
      color: "green",
    }),
    desenvolvimento: createOfficeDpt({
      apps: ["manut", "transf"],
      displayName: "Desenvolvimento",
      id: "desenvolvimento",
      name: "Desenvolvimento",
      positions: ["desenvolvedor"],
      color: "geekblue",
    }),
    diretoria: createOfficeDpt({
      apps: ["manut", "transf"],
      displayName: "Diretoria",
      id: "diretoria",
      name: "Diretoria",
      positions: ["diretor-operacoes", "diretor-financeiro"],
      color: "gold",
    }),
  },

  "shop-floor": {
    corte: createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Corte",
      id: "corte",
      machines: { M1: { name: "Guilhotina" } },
      name: "Corte",
      positions: ["cortador-guilhotina"],
      twoLetterId: "CG",
      color: "lime",
    }),
    "corte-solda-luva": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Corte & Solda – Luva",
      id: "corte-solda-luva",
      machines: {
        M1: { name: "Luva 1" },
        M2: { name: "Luva 2" },
        M3: { name: "Luva 3" },
        M4: { name: "Touca" },
      },
      name: "Corte & Solda – Luva",
      positions: [
        "supervisor-producao",
        "lider-turno",
        "auxiliar-producao",
        "operador-mantenedor",
      ],
      twoLetterId: "CL",
      color: "yellow",
    }),
    "corte-solda-saco": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Corte & Solda – Saco",
      id: "corte-solda-saco",
      machines: {
        M1: { name: "Maqplas 1" },
        M2: { name: "Maqplas 2" },
        M3: { name: "Maqplas 3" },
        M4: { name: "Maqplas 4" },
      },
      name: "Corte & Solda – Saco",
      positions: [
        "supervisor-producao",
        "lider-turno",
        "auxiliar-producao",
        "operador-mantenedor",
      ],
      twoLetterId: "CM",
      color: "yellow",
    }),
    dobra: createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Dobra",
      id: "dobra",
      machines: {
        M1: { name: "Dobra 1" },
        M2: { name: "Dobra 2" },
        M3: { name: "Dobra 3" },
        M4: { name: "Dobra 4" },
        M5: { name: "Dobra 5" },
        M6: { name: "Dobra 6" },
        M7: { name: "Dobra 7" },
      },
      name: "Dobra",
      positions: ["lider-turno", "auxiliar-producao"],
      twoLetterId: "DB",
      color: "green",
    }),
    ekoplasto: createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "EkoPlasto",
      id: "ekoplasto",
      machines: {
        EL: { name: "Elétrica..." },
        M1: { name: "Aglutinador" },
        M2: { name: "Extrusora Recicladora" },
        M3: { name: "Moinho a Seco" },
        M4: { name: "Moinho da Lavagem" },
        M5: { name: "Secadora" },
        M6: { name: "Tanque de Lavagem" },
        M7: { name: "Ventoinhas" },
        M8: { name: "Sem-fins" },
      },
      name: "EkoPlasto",
      positions: ["gerente-manutencao"],
      twoLetterId: "EK",
      color: "orange",
    }),
    extrusao: createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Extrusão",
      id: "extrusao",
      machines: {
        M1: { name: "Extrusora 1" },
        M2: { name: "Extrusora 2" },
        M3: { name: "Extrusora 3" },
        M4: { name: "Extrusora Plana" },
      },
      name: "Extrusão",
      positions: [
        "supervisor-producao",
        "extrusor-1",
        "extrusor-2",
        "auxiliar-extrusao",
      ],
      twoLetterId: "EX",
      color: "cyan",
    }),
    "flexografia-papel": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Flexografia – Papel",
      id: "flexografia-papel",
      machines: {
        M1: { name: "Etirama 1" },
        M2: { name: "Etirama 2" },
        M3: { name: "Etirama 3" },
      },
      name: "Flexografia – Papel",
      positions: ["lider-turno", "impressor-flexo-2"],
      twoLetterId: "IF",
      color: "geekblue",
    }),
    "flexografia-plastico": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Flexografia – Plástico",
      id: "flexografia-plastico",
      machines: {
        M1: { name: "Drucken" },
      },
      name: "Flexografia – Plástico",
      positions: ["operador-flexo"],
      twoLetterId: "ID",
      color: "geekblue",
    }),
    "kit-automatico": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Kit Automático",
      id: "kit-automatico",
      machines: {
        D1: { name: "Dobradeira 1" },
        D10: { name: "Dobradeira 10" },
        D11: { name: "Dobradeira 11" },
        D12: { name: "Dobradeira 12" },
        D13: { name: "Dobradeira 13" },
        D14: { name: "Dobradeira 14" },
        D15: { name: "Dobradeira 15" },
        D16: { name: "Dobradeira 16" },
        D2: { name: "Dobradeira 2" },
        D3: { name: "Dobradeira 3" },
        D4: { name: "Dobradeira 4" },
        D5: { name: "Dobradeira 5" },
        D6: { name: "Dobradeira 6" },
        D7: { name: "Dobradeira 7" },
        D8: { name: "Dobradeira 8" },
        D9: { name: "Dobradeira 9" },
        M1: { name: "Joke 1" },
        M2: { name: "Joke 2" },
        M3: { name: "Joke 3" },
        M4: { name: "Joke 4" },
        M5: { name: "Joke 5" },
        M6: { name: "Joke 6" },
        M7: { name: "Joke 7" },
      },
      name: "Kit Automático",
      positions: [
        "supervisor-producao",
        "lider-turno",
        "operador-2",
        "auxiliar-producao",
      ],
      twoLetterId: "KA",
      color: "blue",
    }),
    "kit-manual": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Kit Manual",
      id: "kit-manual",
      machines: {
        M1: { name: "FlowPack 1" },
        M2: { name: "FlowPack 2" },
      },
      name: "Kit Manual",
      positions: [
        "supervisor-producao",
        "lider-turno",
        "auxiliar-producao",
        "operador-mantenedor",
      ],
      twoLetterId: "FK",
      color: "volcano",
    }),
    "off-set": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Off-Set",
      id: "off-set",
      machines: {
        M1: { name: "Rotateck" },
        M2: { name: "Maqforms" },
        M3: { name: "DIDE 1" },
        M4: { name: "DIDE 2" },
      },
      name: "Off-Set",
      positions: ["impressor-flexo-2", "encarregado-off-set"],
      twoLetterId: "IO",
      color: "magenta",
    }),
    reciclagem: createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Reciclagem",
      id: "reciclagem",
      machines: { M1: { name: "Recicladora" } },
      name: "Reciclagem",
      positions: [
        "supervisor-producao",
        "lider-turno",
        "auxiliar-producao",
        "assistente-reciclagem",
        "operador-reciclagem-1",
        "operador-reciclagem-2",
      ],
      twoLetterId: "RC",
      color: "red",
    }),
    "super-kit": createShopFloorDpt({
      apps: ["manut", "transf"],
      displayName: "Super Kit",
      id: "super-kit",
      machines: {
        M1: { name: "FlowPack 1" },
        M2: { name: "FlowPack 2" },
      },
      name: "Super Kit",
      positions: [
        "supervisor-producao",
        "lider-turno",
        "auxiliar-producao",
        "operador-mantenedor",
      ],
      twoLetterId: "FK",
      color: "purple",
    }),
  },
};

export default DEPARTMENTS;
