import type { Na3DepartmentId } from "../modules/na3-types";

export const MACHINE_ISSUES: Record<Na3DepartmentId<"shop-floor">, string[]> = {
  corte: ["Troca do parafuso de segurança", "Problema na correia do motor"],
  "corte-solda-luva": [
    "Eixo partido",
    "Falta de molas",
    "Molde",
    "Máquina desligando",
    "Faca falhando",
    "Máquina embuchando",
    "Barra de estática",
    "Parafuso solto/Quebra de parafuso",
    "Misturador parando",
    "Máquina variando",
    "Controlador de temperatura",
    "Fio solto/Mau contato",
    "Trocar pino quebrado",
    "Pino quente não está esquentando",
    "Troca da resistência do pino",
    "Problema no termopar",
  ],
  "corte-solda-saco": [
    "Troca do alinhador",
    "Cabeçote superior",
    "Cabeçote inferior",
    "Vazamento de ar",
    "Máquina não está ligando",
    "Material enrugado",
    "Esteira não está ligando",
    "Barra de estática",
    "Erro no servo-driver",
    "Instalação de pé de galinha",
    "Problema no destacador",
    "Abrir rosca na castanha",
    "Pistão solto",
    "Esticador da corrente",
    "Painel",
    "Fio solto/Mau contato",
    "Solda fraca",
    "Barramento",
    "Trocar pino quebrado",
    "Pino quente não está esquentando",
    "Troca da resistência do pino",
    "Problema no rolo selador",
    "Problema no rolo puxador",
  ],
  dobra: [
    "Rolo da dobradeira",
    "Troca de correia",
    "Engrenagem da dobradeira",
    "Mancal com folga",
    "Fio solto/Mau contato",
  ],
  ekoplasto: [],
  extrusao: [
    "Pirômetro da matriz",
    "Troca de mangueira",
    "Vazamento de ar",
    "Problema no rolamento",
    "Motor principal",
    "Ventoinha",
    "Rolo banana",
    "Mancal com rosca espanada",
    "Braço do desbobinador",
    "Caixa redutora",
    "Fio solto/Mau contato",
    "Resistência queimada",
    "Ligar/Desligar resistência",
    "Troca de resistência",
    "Eixo vazando ar",
    "Troca da válvula do eixo",
    "Problema na matriz",
  ],
  "flexografia-papel": [
    "Rolo de alinox",
    "Rolamento",
    "Bateção parou",
    "Secagem",
    "Falta de fase",
    "Vazamento de ar",
    "Erro no inversor",
    "Problema na tensão",
    "Tensão do desbobinador",
    "Vídeo-scan",
    "Trocar acoplamento do encoder",
    "Emergência com mau contato",
    "Porta-clichê",
    "Regulagem na pressão",
    "Proteção do eixo",
    "Fio solto/Mau contato",
  ],
  "flexografia-plastico": [
    "Rolo de alinox",
    "Rolamento",
    "Secagem",
    "Bomba de tinta",
    "Falta de fase",
    "Vazamento de ar",
    "Erro no inversor",
    "Entrada de tinta da blade",
    "Emergência com mau contato",
    "Porta-clichê",
    "Regulagem na pressão",
    "Proteção do eixo",
    "Fio solto/Mau contato",
  ],
  "kit-automatico": [
    "Estação de selagem/rolagem",
    "Faca da dobradeira",
    "Fio solto/Mau contato",
    "Parafuso da flange ou quebra de parafuso",
    "Cabo da temperatura",
    "Cardan da dobradeira",
    "Folga no rolo (puxador de apara)",
    "Folga no rolo (dobradeira)",
    "Folga no rolo (carrinho)",
    "Flap do carrinho",
    "Motor desbobinador parou (papel)",
    "Motor desbobinador parou (plástico – molde inferior)",
    "Motor desbobinador parou (plástico – molde superior)",
    "Regulagem sensor",
    "Alarme do molde/controlador/servo",
    "Mancal com folga",
    "Carrinho da dobradeira",
    "Polia do servo",
    "Castanha do alinhador de papel",
    "Engrenagem da dobradeira",
    "Servo motor",
    "Correia do carrinho",
    "Correia da dobradeira",
    "Rolamento estourado",
    "Rolamento travado",
    "Troca do rolamento",
    "Folga na área do rolamento",
    "Folga na área da chaveta",
    "Esteira da dobradeira",
    "Controlador de temperatura",
    "Troca do borne termoplástico",
    "Troca de terminais",
    "Troca do sindal",
    "Troca do potenciômetro bailário",
    "Troca do sensor/contador",
  ],
  "kit-manual": [
    "Máquina desarmando",
    "Máquina fechando curto",
    "Resistência do forno",
    "Faca",
    "Esteira do forno",
  ],
  "off-set": [
    "Troca de fonte",
    "Molhador de bateria",
    "Alinhador (FIFE) do desbobinador",
    "Verificar motor",
    "Fio solto/Mau contato",
  ],
  reciclagem: [
    "Rosca desarmando",
    "Parafuso do eixo afrouxando",
    "Fio solto no disjuntor",
    "Parafuso solto/Quebra de parafuso",
    "Ventoinha em curto",
    "Troca de óleo",
    "Fio solto/Mau contato",
    "Resistência queimada",
    "Troca de resistência",
    "Ligar/Desligar resistência",
    "Embuchamento",
    "Misturador",
  ],
  "super-kit": [
    "Máquina desarmando",
    "Máquina fechando curto",
    "Resistência do forno",
    "Faca",
    "Esteira do forno",
  ],
};

export default MACHINE_ISSUES;
